// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpc/foods/foods.proto

package foods

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FoodsClient is the client API for Foods service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoodsClient interface {
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type foodsClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodsClient(cc grpc.ClientConnInterface) FoodsClient {
	return &foodsClient{cc}
}

func (c *foodsClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/foods.Foods/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodsServer is the server API for Foods service.
// All implementations must embed UnimplementedFoodsServer
// for forward compatibility
type FoodsServer interface {
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	mustEmbedUnimplementedFoodsServer()
}

// UnimplementedFoodsServer must be embedded to have forward compatible implementations.
type UnimplementedFoodsServer struct {
}

func (UnimplementedFoodsServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedFoodsServer) mustEmbedUnimplementedFoodsServer() {}

// UnsafeFoodsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodsServer will
// result in compilation errors.
type UnsafeFoodsServer interface {
	mustEmbedUnimplementedFoodsServer()
}

func RegisterFoodsServer(s grpc.ServiceRegistrar, srv FoodsServer) {
	s.RegisterService(&Foods_ServiceDesc, srv)
}

func _Foods_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodsServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foods.Foods/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodsServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Foods_ServiceDesc is the grpc.ServiceDesc for Foods service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Foods_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foods.Foods",
	HandlerType: (*FoodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _Foods_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/foods/foods.proto",
}
