/**
 * @fileoverview gRPC-Web generated client stub for foods
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: src/protos/foods.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_protos_foods_pb from '../../src/protos/foods_pb';


export class FoodsServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAll = new grpcWeb.MethodDescriptor(
    '/foods.FoodsService/GetAll',
    grpcWeb.MethodType.UNARY,
    src_protos_foods_pb.GetAllRequest,
    src_protos_foods_pb.GetAllResponse,
    (request: src_protos_foods_pb.GetAllRequest) => {
      return request.serializeBinary();
    },
    src_protos_foods_pb.GetAllResponse.deserializeBinary
  );

  getAll(
    request: src_protos_foods_pb.GetAllRequest,
    metadata: grpcWeb.Metadata | null): Promise<src_protos_foods_pb.GetAllResponse>;

  getAll(
    request: src_protos_foods_pb.GetAllRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_protos_foods_pb.GetAllResponse) => void): grpcWeb.ClientReadableStream<src_protos_foods_pb.GetAllResponse>;

  getAll(
    request: src_protos_foods_pb.GetAllRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_protos_foods_pb.GetAllResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/foods.FoodsService/GetAll',
        request,
        metadata || {},
        this.methodDescriptorGetAll,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/foods.FoodsService/GetAll',
    request,
    metadata || {},
    this.methodDescriptorGetAll);
  }

}

