app:
  api: 1326
  name: "auth-service"
  grpc: 50002

mongo:
  username: "root"
  password: "12345678"
  host: "localhost"
  port: 27017
  database: "user"

jwt:
  pub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzFxaifNr747MDH+s6SkS
    fPOH3EBxc062xCjzZLUpg4Mo+0RIqSWmUy0B4FMsPZJLm8/lH8Z0L+luOpKWxHnK
    y6c9m41g+ACEUrVeO3QeZOias30EGZn2DXkHKCvVc6eGO8bAhjSLypQk5qKUNZxO
    Q2rGKX8RFnLO8gY8mpAWCtFYPKUqBQgCnsw1HHC4LVXvTErO6hRwwETZEjHEyyPN
    O3t6jHswNWwNeF6TWq358C5O0An8oKAbUWYAadJ+P3rxsApZr2y2GJ6eHakJ2WOt
    S6oPvK2d4EWEQJj1CinRLEW2eVMcsDcUmSUA9/Y4J5NQ4tvRuv1OWn9mf8lrKhOu
    oQIDAQAB
    -----END PUBLIC KEY-----
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAzFxaifNr747MDH+s6SkSfPOH3EBxc062xCjzZLUpg4Mo+0RI
    qSWmUy0B4FMsPZJLm8/lH8Z0L+luOpKWxHnKy6c9m41g+ACEUrVeO3QeZOias30E
    GZn2DXkHKCvVc6eGO8bAhjSLypQk5qKUNZxOQ2rGKX8RFnLO8gY8mpAWCtFYPKUq
    BQgCnsw1HHC4LVXvTErO6hRwwETZEjHEyyPNO3t6jHswNWwNeF6TWq358C5O0An8
    oKAbUWYAadJ+P3rxsApZr2y2GJ6eHakJ2WOtS6oPvK2d4EWEQJj1CinRLEW2eVMc
    sDcUmSUA9/Y4J5NQ4tvRuv1OWn9mf8lrKhOuoQIDAQABAoIBAFXaBn8lsBZ3muk1
    SeK5ynaLqGuy9vZF/ynxOi74nHQPScwlJ5FHq9QNeFhRGKjVKMZQVCVBLdZi7lfU
    9VmdAMEFhTAv+Ki3Lt/AKdI4OfySa0s0HeDTeTa3vXX21Dk+C3pZSNAYixGTotzx
    N+o9u/M+i/kq1HblzGKIlDUqitgH0idu4fEq2XdnovalE+zo5mMiVda6bYPqJNO9
    /ePWjoq5Pd2ShZJ0mBumXDAuueppKM6rGNMe0tEDpOj7OZ6oFl5E+Lwer5UE0t4K
    YHnvFqk5TeZ4U/GLTPYcepLNH0nSKqphXTuibWS0aUPREQeU3k6sAsBP8TO8PmoR
    2GJjcEECgYEA5bYSxm2o4VBetEqda1LUIHZmmJohZz55M9KQ254EbxWz6ZNR1g10
    CEabzo4jHMKQKx8BnrDA6DDoyPunWcoKmRm8HoOcvLotJ9yH+TZB0f134HKVzAuu
    8SrG1k8cpXIc9KrCELuTEpH0gKuUdrQXtcnpW0HJq3r2jbLW3cgMxiUCgYEA47+U
    Rekm3qKo6m1BQZpN2xJcVjbN6opj6Dc74Rad1t1K0LIxiug8p6bI1S1wxaleIywk
    ht2wDt17Q7xF0qdWCn82/qXZKd8XHvkJkp/J9sBEferusufS8+xDQUosWzuKWOFP
    xsRnhbyjQr3fm/RW123M2OuoL23I35XcsnZWB80CgYEAi7qyNwOTe+MAiJjuos8S
    e+Cpzd/Lu9qzrUNDnGPFfLDt7IIRgKxUTYht1Dp/v0nWmnRU7uvDnDnMEB2MEcEl
    qzWNSd5zJBX3y8yI5Z4McajGF8B7wE/HDaogo1IiMb11QZrxS25eKyifWvmD6KTp
    20nD6h/dhbLZcR49N1Et/AUCgYA6u5w8Tz1D6wTOt/A9P9LWLSz82tNNqfTL3Pqn
    OJLp51W07k9SeEO0JJHkT/ymLOBnB6o/0Ynmu31fYX1MLvVEbbw7/X88ihjHVwf9
    9RE7fifrpRt7rcc8OnC5tKwttvQdqbVOGDZuSdB8lMTGzkNa+Sj7xAIygQhtiJNK
    vrO+/QKBgFNF+OFSq8xjDRfTcas7805l5koQBQ/0yqQY7RXb4beuDzber2MAl89E
    uQLqfphaBpxQGeCoTqhoD9QKe3DWcWKWIPbEx3Bj4u3Bjv673zIcWOWayAZA/Vtw
    +0DyLay71Tc57mKz+a/FFc/L6cF76lF4vVoIjGrRNfk1j55D/1qf
    -----END RSA PRIVATE KEY-----